{% set name = "mc3" %}
{% set version = "3.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mc3-{{ version }}.tar.gz
  sha256: 518dc4f33a016c553fd3e7f0f3b14c753aa0ca4a17ac817c8a5bff4840baedbf

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<35]
  entry_points:
    - mc3 = mc3.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
  run:
    - matplotlib-base >=3.3.4
    - numpy >=1.19.5
    - python
    - scipy >=1.5.4

test:
  imports:
    - mc3

about:
  home: https://github.com/pcubillos/mc3
  summary: Multi-core Markov-chain Monte Carlo package.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/mc3
  doc_url: https://mc3.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
