{% set name = "mc3" %}
{% set version = "3.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mc3-{{ version }}.tar.gz
  sha256: a726c981f32b46990aee2869051306a0bbd23562eaab109c418a535096374cd6

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<35]
  entry_points:
    - mc3 = mc3.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - matplotlib-base >=2.0
    - numpy >=1.15.0
    - python
    - scipy >=0.17.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - mc3

about:
  home: https://github.com/pcubillos/mc3
  summary: Multi-core Markov-chain Monte Carlo package.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pcubillos/mc3
  doc_url: https://mc3.readthedocs.io/en/latest/index.html

extra:
  recipe-maintainers:
    - pcubillos
